name: teste-todolist

on: [push, pull_request]
jobs:
  build:
     runs-on: ubuntu-latest
     timeout-minutes: 5
     steps:
       -  name: Checkout
          uses: actions/checkout@master
          
       -  name: Use Node 
          uses: actions/setup-node@v1
          with:
            node-version: 10.x
            
       - name: Install
         run: npm install
         
       - name: DockerHub Login
         uses: docker/login-action@v1.10.0
         with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASS }}

       - name: Build Artifact Back
         uses: docker/build-push-action@v2.6.1
         with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: |
            dsobootcamp/todolistback:${{ github.run_number }}
            dsobootcamp/todolistback:latest
       
       - name: Build Artefacts
         uses: docker/build-push-action@v2.6.1
         with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: |
            dsobootcamp/todolistfront:${{ github.run_number }}
            dsobootcamp/todolistfront:latest